name: Deploy gh-pages

on:
  push:
    branch:
    - master

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      CI_PRI      : ${{secrets.CI_PRI}}
      USER_NAME   : Matthew Ng
      USER_EMAIL  : ngmhmatthew@gmail.com
      PUBLISH_DIR : ./build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Test 1
      run: |
        ls
    - name: Test 2
      run: |
        mkdir -p ~/.ssh
        echo -n $CI_PRI | base64 -d > ~/.ssh/id_ci_pri
        chmod 400 ~/.ssh/id_ci_pri
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ci_pri
        git remote set-url origin git@github.com:m2ng/m2ng.githun.io.git
        ls
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: npm install
    #   run: |
    #     npm install
