name: Deploy gh-pages

on:
  push:
    branch:
    - master

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      CI_PRI      : ${{secrets.CI_PRI}}
      USER_NAME   : Matthew Ng
      USER_EMAIL  : ngmhmatthew@gmail.com
      PUBLISH_DIR : ./build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Test 1
      run: |
        ls
        echo $PWD
    - name: Test 2
      run: |
        mkdir -p ~/.ssh
        echo "github.com ssh-ed25519 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU" >> ~/.ssh/known_hosts
        echo -n $CI_PRI | base64 -d > ~/.ssh/id_ci_pri
        chmod 400 ~/.ssh/id_ci_pri
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ci_pri
        git remote set-url origin git@github.com:m2ng/m2ng.github.io.git
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build CV
      run: |
        BUILD_PATH="$PWD/build"
        mkdir -p $BUILD_PATH
        cd apps/main
        npm install
        npm run build
        ls $BUILD_PATH
    - name: Upload built CV
      uses: actions/upload-artifact@v3
      with:
        name: main-app
        path: $BUILD_PATH